Add files via upload
klublubiteley/Laba1 pull request #4
Opened 2024-10-31 18:58 UTC by klublubiteley

2024-10-31 19:06 UTC, klublubiteley commented on Лабораторная 2/2-2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов: {needed_capital}")
у меня в pycharm есть пустая строчка, я не знаю, почему она здесь не высвечивается( 
не знаю, откроется ли скрин
![2024-10-31_22-03-49](https://github.com/user-attachments/assets/6dccff1d-06fb-489b-98e3-2adc9d2b9001)

2024-10-31 19:07 UTC, klublubiteley commented on Лабораторная 2/2-1.py
> +print(f'Количество месяцев, которое можно протянуть без долгов: {res}')
пустая строчка(( 
она есть, но её нет :(
![2024-10-31_22-07-09](https://github.com/user-attachments/assets/dc5fd9ad-5edf-4193-9552-608e519f55f8)

2024-11-01 19:19 UTC, rmushkin commented on Лабораторная 2/2-1.py
> +print(f'Количество месяцев, которое можно протянуть без долгов: {res}')
Всё хорошо! Строчка есть. Гитхаб её не показывает. А вот если строчки нет, то тон рисует вместо неё жирный красный крест (и в этом случае я делал замечание). Теперь всё хорошо.

2024-11-01 19:19 UTC, rmushkin commented on Лабораторная 2/2-2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов: {needed_capital}")
Всё вижу, спасибо) Ответил выше.

2024-11-01 19:27 UTC, rmushkin requested changes
Есть две ошибки! Пожалуйста, исправьте.

2024-11-01 19:27 UTC, rmushkin commented on Лабораторная 2/2-1.py
> +        return 0  # Невозможно прожить ни одного месяца, если денег нет
по условиям не совсем ясно, что случается раньше - зарплата или расходы. Но вообще говоря, зарплата может покрыть расходы за первый месяц, и тогда без подушки прожить вполне можно.

2024-11-01 19:27 UTC, rmushkin commented on Лабораторная 2/2-2.py
> +        if total_months > 0:
Кажется, вы опечатались и сравниваете не то (total_months - это же не первый месяц, это вообще количество месяцев, не зависящее от положения в цикле)

2024-11-01 20:30 UTC, closed without merging